services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - VIRTUAL_HOST=krmndemo.online
      - LETSENCRYPT_HOST=krmndemo.online
      - LETSENCRYPT_EMAIL=krmn28aws@gmail.com
    restart: always
    networks:
      - webproxy

networks:
  webproxy:
    external: true